### ISSUE TITLE
SearXNG not starting on docker

### ISSUE THREAD

**Issue by Eirikr70** [searxng/searxng-docker#13]
Hello,
Sorry to tell that I didn't succeed in starting SearXNG on docker following today's update. My system is ARM64. I couldn't even enter the container to change the authorizations of the incriminated file. I have come back to a former version.
Here is my docker-compose log
```
eric@vault:~/searx $ sudo docker-compose logs
Attaching to searx
searx      | SearXNG version 2022.03.21-b14ed494
searx      | ⚠️  Check new version /etc/searxng/uwsgi.ini.new to make sure SearXNG is working properly
searx      | ⚠️  Check new version /etc/searxng/settings.yml.new to make sure SearXNG is working properly
searx      | Listen on 0.0.0.0:8080
searx      | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
searx      | [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
searx      | open("/var/log/uwsgi/uwsgi.log"): Permission denied [core/logging.c line 288]
searx      | SearXNG version 2022.03.21-b14ed494
searx      | ⚠️  Check new version /etc/searxng/uwsgi.ini.new to make sure SearXNG is working properly
searx      | ⚠️  Check new version /etc/searxng/settings.yml.new to make sure SearXNG is working properly
searx      | Listen on 0.0.0.0:8080
searx      | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
searx      | [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
searx      | open("/var/log/uwsgi/uwsgi.log"): Permission denied [core/logging.c line 288]
searx      | SearXNG version 2022.03.21-b14ed494
searx      | ⚠️  Check new version /etc/searxng/uwsgi.ini.new to make sure SearXNG is working properly
searx      | ⚠️  Check new version /etc/searxng/settings.yml.new to make sure SearXNG is working properly
searx      | Listen on 0.0.0.0:8080
searx      | [uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
searx      | [uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
searx      | open("/var/log/uwsgi/uwsgi.log"): Permission denied [core/logging.c line 288]
...
```
And the docker-compose file
```
version: '3.7'

services:
  searxng:
    container_name: searx
    image: searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - BASE_URL=https://localhost:8880/
      - TZ=Europe/Paris
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    ports:
      - 8880:8080
    restart: unless-stopped
```
