### ISSUE TITLE
tor don't work

### ISSUE THREAD

**Issue by lmaddox** [searxng/searxng-docker#250]
```
proxies:
    all://:
      - socks5h://192.168.2.250:9050
  using_tor_proxy: true
  extra_proxy_timeout: 10
 ```
 
 
 ```
 #caddy: # broken
 searxng:
    container_name: searxng
    image:          docker.io/searxng/searxng:latest
    restart:        unless-stopped
    #networks: # just don't work (tm)
    #  - searxng
    network_mode:    "host"                         # 3142
    ports:
      #- "127.0.0.1:8080:8080"
      - "8080:8080"
    #env_file: # that'd be a lot of settings to keep in the root .env
    #  - searx.d/.env # so it needs to go in a subdir
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      #- SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/ # broken redirect
      #- SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-miller.innovanon.com}/ # https doesn't work
      - SEARXNG_BASE_URL=http://${SEARXNG_HOSTNAME:-miller.innovanon.com:8080}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
  ```
