### ISSUE TITLE
Bad gateway when using with traefik for ssl certs

### ISSUE THREAD

**Issue by fahadshery** [searxng/searxng-docker#262]
Hi,

I literally found out about this project and instantly fell in love with it! This needs to be part of my home lab! 
So I am running traefik to manage my docker containers. 
I have made this container to be part of traefik network. 
Here is the docker compose file for searxng:
```
version: '3.9'

services:

  redis:
    container_name: redis
    image: docker.io/valkey/valkey:7-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /home/fahadshery/searxng/valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
        
  searxng:
    image: searxng/searxng
    container_name: searxng
    mem_limit: 8g
    cpu_shares: 2048
    depends_on:
      - 'redis'
    environment:
      - REDIS_URL=redis://redis:6379/0
      - TZ=Europe/London
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/fahadshery/searxng:/etc/searxng:rw 
    restart: always
    ports:
      - 5147:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`search.local.fahadusman.com`)"
      - "traefik.http.routers.searxng.entrypoints=https"
      - "traefik.http.routers.searxng.tls=true"
      - "traefik.http.services.searxng.loadbalancer.server.port=5147"
    networks:
      - proxy

networks:
  proxy:
    external: true
```

I have defined entry points of `https` in traefik. but I am getting `bad gateway` error.
I have looked at [here](https://github.com/tomMoulard/make-my-server/blob/master/searxng/docker-compose.searxng.yml), and [here](https://github.com/techno-tim/techno-tim.github.io/tree/master/reference_files/traefik-portainer-ssl/traefik) but no luck...

here are the logs:
```
SearXNG version 2024.8.15+8e985aea8
Use existing /etc/searxng/uwsgi.ini
Use existing /etc/searxng/settings.yml
Listen on 0.0.0.0:8080
[uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
[uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
*** Starting uWSGI 2.0.25.1 (64bit) on [Thu Aug 15 14:08:00 2024] ***
compiled with version: 13.2.1 20240309 on 17 May 2024 06:11:37
os: Linux-5.15.0-1064-kvm #69-Ubuntu SMP Wed Jul 17 12:14:19 UTC 2024
nodename: ef7b998842fc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 6
current working directory: /usr/local/searxng
detected binary path: /usr/sbin/uwsgi
setgid() to 977
setuid() to 977
chdir() to /usr/local/searxng/searx/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1390 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 3
Python version: 3.12.3 (main, Apr 18 2024, 07:52:31) [GCC 13.2.1 20240309]
Python main interpreter initialized at 0x7f3b0457e688
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 844704 bytes (824 KB) for 24 cores
*** Operational MODE: preforking+threaded ***
added /usr/local/searxng/ to pythonpath.
spawned uWSGI master process (pid: 7)
spawned uWSGI worker 1 (pid: 10, cores: 4)
spawned uWSGI worker 2 (pid: 12, cores: 4)
spawned 4 offload threads for uWSGI worker 1
spawned uWSGI worker 3 (pid: 17, cores: 4)
spawned 4 offload threads for uWSGI worker 2
spawned uWSGI worker 4 (pid: 21, cores: 4)
spawned uWSGI worker 5 (pid: 22, cores: 4)
spawned uWSGI worker 6 (pid: 26, cores: 4)
spawned 4 offload threads for uWSGI worker 6
spawned 4 offload threads for uWSGI worker 5
spawned 4 offload threads for uWSGI worker 4
spawned 4 offload threads for uWSGI worker 3
2024-08-15 14:08:01,635 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f3b0457e688 pid: 12 (default app)
2024-08-15 14:08:01,639 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f3b0457e688 pid: 17 (default app)
2024-08-15 14:08:01,648 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f3b0457e688 pid: 21 (default app)
2024-08-15 14:08:01,653 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f3b0457e688 pid: 22 (default app)
2024-08-15 14:08:01,664 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f3b0457e688 pid: 26 (default app)
2024-08-15 14:08:01,690 WARNING:searx.botdetection.config: missing config file: /etc/searxng/limiter.toml
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x7f3b0457e688 pid: 10 (default app)
```
any pointers?
