### ISSUE TITLE
Firefox could not download the search plugin

### ISSUE THREAD

**Issue by spaelling** [searxng/searxng-docker#32]
![image](https://user-images.githubusercontent.com/871412/177212653-d53ae1db-dd4b-4959-9dc3-a4f803e11adf.png)

I wanted to use my newly minted searxng site as the default search engine in Firefox, but it seems the opensearch.xml is missing

[https://developer.mozilla.org/en-US/docs/Web/OpenSearch](https://developer.mozilla.org/en-US/docs/Web/OpenSearch)

**Comment by mrpaulblack** [comment]
Hi @spaelling ,
When I try to open https://searxng.azurewebsites.net/opensearch.xml?method=POST&autocomplete= I can see that the env vars in the response are configured weirdly:

```xml
<?xml version="1.0" encoding="utf-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
  <ShortName>searxng</ShortName>
  <Description>a privacy-respecting, hackable metasearch engine</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image>https://${searxng_hostname:-localhost}/static/themes/simple/img/favicon.png</Image>
  <LongName>searx metasearch</LongName>
    <Url rel="results" type="text/html" method="post" template="https://${searxng_hostname:-localhost}/search">
        <Param name="q" value="{searchTerms}" />
    </Url>

  <Url type="application/opensearchdescription+xml"
      rel="self"
      template="/opensearch.xml?method=POST&amp;autocomplete=" />
</OpenSearchDescription>
```

Just to give you a start: Can you check if the environment vars are setup corectly? If you use docker you can enter the container and print all its env vars with with `docker exec -it [container_id] printenv`.

**Comment by spaelling** [comment]
its running inside an Azure web app, so I have not access to the docker host. I think it might be a general issue with environment variables I have to look into. I tried hardcoding the `searxng_hostname` in the docker compose file, and now the opensearch.xml seems to render correctly.

below is what I ended up having working with Azure web apps (network configuration is not supported, so commented that out) - also very limited on port mappings.

```yaml
version: '3.7'
services:
  caddy:
    container_name: caddy
    image: caddy:2-alpine
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      # - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME} 
      - SEARXNG_HOSTNAME=searxng.azurewebsites.net
      # SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost:80}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly no
    # networks:
    #   - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    # networks:
    #   - searxng
    ports:
     - "8080:8080" #"127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      # - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME}/
      - SEARXNG_BASE_URL=https://searxng.azurewebsites.net/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
# networks:
#   searxng:
#     ipam:
#       driver: default
volumes:
  caddy-data:
  caddy-config:
```
