### ISSUE TITLE
Autocomplete only partially working

### ISSUE THREAD

**Issue by Azmodeszer** [searxng/searxng-docker#329]
I found a few issues here referencing this, but none of the solutions did the trick for me.

I have a self-hosted instance deployed via docker-compose/Portainer stack. Everything seems to work fine, except for autocomplete. When I type something in the instance's search bar itself, it works, but when I use my browser's (Firefox) address bar, it does not. I have successfully configured searXNG as my default search engine in Firefox and `https://myinstance.com/autocompleter?q=word` returns a valid JSON with suggestions. duckduckgo is also set in my searXNG's settings to use for autocomplete.

The stack I deployed:
```
services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "8282:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
      - /home/azmodes/searxng/settings.yml:/etc/searx/settings.yml #I had to force this, because some settings didn't get applied otherwise
      - /home/azmodes/searxng/favicons.toml:/usr/local/searxng/searx/favicons/favicons.toml #same here, without this no list of resolvers to select from would show up
    environment:
      - SEARXNG_BASE_URL=https://myinstance.com/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
      - AUTOCOMPLETE=duckduckgo
    #  - SEARXNG_LIMITER=true
    #  - SEARXNG_PUBLIC_INSTANCE=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:

volumes:
  valkey-data2:
```

I'm a bit of a noob with docker/compose, so maybe some of the adjustments here are to blame.

Thanks.
