### ISSUE TITLE
Ngnix in stead of Caddy

### ISSUE THREAD

**Issue by Faeldra** [searxng/searxng-docker#39]
Hi, 

Im running a Rasberry Pi 4b OMV Docker - Portainer. 
and have Ngnix running as a reversed Proxy, 

Need some tips to get it running. I have removed the Caddy config but its not accesable.  ( 502 Bad Gateway) 

- Ngnix added the correct IP and Port
- Portforwarding in the modem/Router (8074)
- Domain with correct forward to Router.

Ive installed this in the home directory of the pi. 

Do i eddit the .env? (i have but there it still does not work)
the directory /var/lib/redis is not beeing made on the system is this a problem?

docker-compose.yaml

version: '3.7'

services:

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
     - "127.0.0.1:8074:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
networks:
  searxng:
    ipam:
      driver: default

.env

# By default listen on https://localhost
# To change this:
# * uncomment SEARXNG_HOSTNAME, and replace <host> by the SearXNG hostname
# * uncomment LETSENCRYPT_EMAIL, and replace <email> by your email (require to create a Let's Encrypt certificate)

SEARXNG_HOSTNAME=mysite.com
LETSENCRYPT_EMAIL=mymail@adress.com

Logs.
Regis.
1:C 19 Jul 2022 09:44:56.459 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 19 Jul 2022 09:44:56.459 # Redis version=7.0.4, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 19 Jul 2022 09:44:56.459 # Configuration loaded
1:M 19 Jul 2022 09:44:56.461 * monotonic clock: POSIX clock_gettime
1:M 19 Jul 2022 09:44:56.463 * Running mode=standalone, port=6379.
1:M 19 Jul 2022 09:44:56.464 # Server initialized
1:M 19 Jul 2022 09:44:56.464 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 19 Jul 2022 09:44:56.470 * Ready to accept connections

Searchxng
SearXNG version 2022.07.18-4d977269
Create /etc/searxng/uwsgi.ini
Use existing /etc/searxng/settings.yml
Listen on 0.0.0.0:8080
[uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
[uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
*** Starting uWSGI 2.0.20 (64bit) on [Tue Jul 19 09:44:57 2022] ***
compiled with version: 11.2.1 20220219 on 21 December 2021 13:20:05
os: Linux-5.10.103-v8+ #1529 SMP PREEMPT Tue Mar 8 12:26:46 GMT 2022
nodename: 90d1c850eb20
machine: aarch64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /usr/local/searxng
detected binary path: /usr/sbin/uwsgi
chdir() to /usr/local/searxng/searx/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1323 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "searxngcache" initialized: 11MB (key: 2136 bytes, keys: 4272000 bytes, data: 8192000 bytes, bitmap: 250 bytes) preallocated ***
uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 4
Python version: 3.10.4 (main, Apr 30 2022, 16:49:16) [GCC 11.2.1 20220219]
Python main interpreter initialized at 0x7fa8399b30
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 603360 bytes (589 KB) for 16 cores
*** Operational MODE: preforking+threaded ***
added /usr/local/searxng/ to pythonpath.
spawned uWSGI master process (pid: 7)
spawned uWSGI worker 1 (pid: 11, cores: 4)
spawned uWSGI worker 2 (pid: 12, cores: 4)
spawned 4 offload threads for uWSGI worker 1
spawned uWSGI worker 3 (pid: 17, cores: 4)
spawned 4 offload threads for uWSGI worker 2
spawned uWSGI worker 4 (pid: 22, cores: 4)
cache sweeper thread enabled
spawned 4 offload threads for uWSGI worker 4
spawned 4 offload threads for uWSGI worker 3
2022-07-19 09:45:02,015 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
2022-07-19 09:45:02,028 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
2022-07-19 09:45:02,098 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
2022-07-19 09:45:02,132 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x7fa8399b30 pid: 11 (default app)
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x7fa8399b30 pid: 17 (default app)
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x7fa8399b30 pid: 12 (default app)
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0x7fa8399b30 pid: 22 (default app)

I have added the line to the uwsqi.ini
# Cache
cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
cache2 = name=searxcache,items=2000,blocks=2000,blocksize=4096,bitmap=1

**Comment by return42** [comment]
Its hard to read, can you please format your comment .. 

- [Basic writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)

**Comment by airdogvan** [comment]
I also have the same problem.  All my other stacks are working with this config but searxng gives me an error.  My docker-compose file:

```
 version: '3.7'

services:

  redis:
    container_name: redisng
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxngng
    image: searxng/searxng:latest
    networks:
      - searxng
      - acme-companion_proxy

    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://xxx.xxx.com
      - VIRTUAL_HOST=xxx.xxx.com
      - LETSENCRYPT_HOST=xxx.xxx.com
      - LETSENCRYPT_EMAIL=xx@xxr.xx
      - VIRTUAL_PORT=8080
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
networks:
  searxng:
  acme-companion_proxy:
    external: true  
  ```
.env file:

  ```
SEARXNG_HOSTNAME=xxx.xxx.com
  ```


Part of the log (too long to quote all of it)

Beginning:

 ```
searxngng  | WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x7f5d92882f78 pid: 10 (default app)
searxngng  | 2023-11-25 19:19:38,781 ERROR:searx.engines.soundcloud: Fail to initialize
searxngng  | Traceback (most recent call last):
searxngng  |   File "/usr/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 190, in connect_tcp
searxngng  |     addr_obj = ip_address(remote_host)
searxngng  |                ^^^^^^^^^^^^^^^^^^^^^^^
searxngng  |   File "/usr/lib/python3.11/ipaddress.py", line 54, in ip_address
searxngng  |     raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
searxngng  | ValueError: 'soundcloud.com' does not appear to be an IPv4 or IPv6 address
 ```

End:

 ```
searxngng  |     self.gen.throw(typ, value, traceback)
searxngng  |   File "/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
searxngng  |     raise mapped_exc(message) from exc
searxngng  | httpx.ConnectError: [Errno -2] Name does not resolve

 ```

As said all my other stacks work with this config, not sure what I'm missing here...
