### ISSUE TITLE
429 Too many requests

### ISSUE THREAD

**Issue by AlexandruCiobanu** [searxng/searxng-docker#55]
Hi,
I have searxng installed in portainer with the latest version as of now and I put it on port 18080. When I open it I see the search ui but as soon as I query for anything I get a too many requests reply back.
```
curl -i -X POST http://localhost:18080/search?q=angular
HTTP/1.1 429 TOO MANY REQUESTS
Content-Type: text/html; charset=utf-8
Content-Length: 17
Server-Timing: total;dur=4.701, render;dur=0
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Download-Options: noopen
X-Robots-Tag: noindex, nofollow
Referrer-Policy: no-referrer
Connection: close

Too Many Requests
```

the log for the container is not indicative as to what the issue may be:
```
SearXNG version 2022.08.09-3d6b098a
Create /etc/searxng/uwsgi.ini
Use existing /etc/searxng/settings.yml
Listen on 0.0.0.0:8080
[uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
[uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
*** Starting uWSGI 2.0.20 (32bit) on [Tue Aug  9 13:18:37 2022] ***
compiled with version: 11.2.1 20220219 on 21 December 2021 13:20:05
os: Linux-5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022
nodename: a1ea282fbc90
machine: armv7l
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /usr/local/searxng
detected binary path: /usr/sbin/uwsgi
chdir() to /usr/local/searxng/searx/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1323 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
*** Cache "searxngcache" initialized: 11MB (key: 2136 bytes, keys: 4272000 bytes, data: 8192000 bytes, bitmap: 250 bytes) preallocated ***
uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 4
Python version: 3.10.5 (main, Jul 25 2022, 15:52:08) [GCC 11.2.1 20220219]
Python main interpreter initialized at 0xb68d3000
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 523040 bytes (510 KB) for 16 cores
*** Operational MODE: preforking+threaded ***
added /usr/local/searxng/ to pythonpath.
spawned uWSGI master process (pid: 6)
spawned uWSGI worker 1 (pid: 10, cores: 4)
spawned uWSGI worker 2 (pid: 11, cores: 4)
spawned 4 offload threads for uWSGI worker 1
spawned uWSGI worker 3 (pid: 16, cores: 4)
spawned 4 offload threads for uWSGI worker 2
spawned uWSGI worker 4 (pid: 22, cores: 4)
cache sweeper thread enabled
spawned 4 offload threads for uWSGI worker 3
spawned 4 offload threads for uWSGI worker 4
2022-08-09 13:18:41,592 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
2022-08-09 13:18:41,614 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
2022-08-09 13:18:41,622 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
2022-08-09 13:18:41,750 ERROR:searx.shared: uwsgi.ini configuration error, add this line to your uwsgi.ini
cache2 = name=searxngcache,items=2000,blocks=2000,blocksize=4096,bitmap=1
WSGI app 0 (mountpoint='') ready in 6 seconds on interpreter 0xb68d3000 pid: 16 (default app)
WSGI app 0 (mountpoint='') ready in 6 seconds on interpreter 0xb68d3000 pid: 22 (default app)
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0xb68d3000 pid: 10 (default app)
WSGI app 0 (mountpoint='') ready in 7 seconds on interpreter 0xb68d3000 pid: 11 (default app)
```

Here is the compose :
```
version: '3.7'

services:

  redis:
    restart: always
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    restart: always
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
     - "127.0.0.1:18080:8080"
    volumes:
      - /home/pi/docker/searxng/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
networks:
  searxng:
    ipam:
      driver: default
```

Any idea why I get that error or how could I see a more detailed log?
