### ISSUE TITLE
Env vars for settings

### ISSUE THREAD

**Issue by mrpaulblack** [searxng/searxng-docker#8]
In the current impl. a settings.yml is mounted as a volume. This makes it harder for maintainers since they need to update the settings.yml every time it changes.

The proposed change would be to set settings as environment variables to make the container sort of stateless...

For example:

`GENERAL_ENGINES=duckduckgo, startpage` only enable those two engines
`IMAGES_ENGINES=bing-images, duckduckgo` images only enable those two engines

**Comment by dalf** [comment]
See https://searxng.github.io/searxng/admin/engines/settings.html#use-default-settings

To keep only duckduckgo (and use a proxy without HTTP2), startpage, bing-images, duckduckgo images:

```yaml
use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - startpage
      - bing-images
      - duckduckgo-images
server:
  secret_key: "v9cvc7q@Mi^N364gEiT$7qPg"
ui:
  default_theme: simple
engines:
  - name: duckduckgo
    network:
      proxy: socks5h://127.0.0.1:1337
      http2: false
```

To sum up: as soon as you specify "use_deefault_settings", the settings.yml becomes a diff with the default configuration. You can replace any value. The exception is the engine definition: you can specify what you keep or remove (see the documentation).

Would it solved the issue?
