### ISSUE TITLE
Change Port (from default Port 80)

### ISSUE THREAD

**Issue by Surgical71** [searxng/searxng-docker#83]
Hi There

I am trying to run this container behind NGINX Proxy manager. I want to change the port but all attempts have failed.
I updated the docker-compose.yaml file but this dis not resolve the issue.

This is the error log in the caddy container:
{"level":"info","ts":1662286771.844921,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"172.18.0.2","remote_port":"53464","proto":"HTTP/1.1","method":"GET","host":"example.mydomain.com","uri":"/","headers":{"Cache-Control":["max-age=0"],"Sec-Ch-Ua-Mobile":["?0"],"Cf-Visitor":["{\"scheme\":\"https\"}"],"Sec-Fetch-Dest":["document"],"Accept-Encoding":["gzip"],"Upgrade-Insecure-Requests":["1"],"Accept-Language":["en-GB,en-US;q=0.9,en;q=0.8"],"Priority":["u=0"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["172.68.186.104"],"Cf-Ray":["7455fcc3a8290700-CPT"],"Dnt":["1"],"Cf-Connecting-Ip":["x.x.x.x"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.115 Safari/537.36"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Cf-Ipcountry":["ZA"],"Sec-Fetch-Site":["none"],"X-Forwarded-For":["172.68.186.104"],"Cdn-Loop":["cloudflare"],"Sec-Ch-Ua":["\"Chromium\";v=\"104\", \" Not A;Brand\";v=\"99\""],"Sec-Ch-Ua-Platform":["\"Windows\""],"Cookie":[],"X-Forwarded-Scheme":["https"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-User":["?1"]}},"user_id":"","duration":0.00000396,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}

NB: I did update my IP's, so current IP's showing is private (Local) IP's

**Comment by benjamin051000** [comment]
I can't figure out how to do this either. Been changing ports in the docker-compose for a while but it doesn't appear to  work...

**Comment by azvampyre** [comment]
//replace ports: - "127.0.0.1:8888:8080" changing 8080 to 8888 or whatever port to listen on and access it from https://yourhostnameorip:8888
	```
searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
      - "8888:8080"
```

**Comment by azvampyre** [comment]
docker-compose.yaml:
```
searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
      **- "<YOURIP>:<YOURPORT>:8080"**
```
Caddyfile:
<add> **`bind <YOURIP>`**
<before> `tls {$SEARXNG_TLS}`
<edit> **`reverse_proxy <YOURIP>:<YOURPORT>`**

I'm using a secondary IP so you just need to replace the ports if you're hosting locally. Otherwise change 127.0.0.1 to 0.0.0.0 or your IP so it can be accessed outside of the Docker network.
