### ISSUE TITLE
need advice: searxng + nginx proxy manager + cloudflare

### ISSUE THREAD

**Issue by ziimro** [searxng/searxng-docker#88]
I figured out how to set up an instance of searxng but im not sure if its properly secure.
what i did is replaced the caddy section in `docker-compose.yaml` with my own
```yaml
  caddy:
    container_name: caddy
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost:80}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - DAC_OVERRIDE
    restart: always
```
i removed the `network-mode: host` since i have port 443 occupied already by nginx-proxy-manager
in `.env` i just used my ~~local ip~~ domain as the `SEARXNG_HOSTNAME` and commented out `LETSENCRYPT_EMAIL` so i can use my end-to-end cloudflare cert.
I have connected searx to my nginx-proxy-manager network so i just pass the container name and the `8080` port, i have and added the ssl cert there too

in the searx section in `docker-compose.yaml` i just changed the ports from `"127.0.0.1:8080:8080"` to:
```yaml
    ports:
     - "8080:8080"
```

Is this a proper way to do it? Is this properly secure?
im passing the 8080 port directly from searxng to nginx-proxy manager, so caddy does nothing right?

**Comment by dalf** [comment]
See https://github.com/searxng/searxng-docker/issues/15

you don't need Caddy, if you already have nginx.

**Comment by ziimro** [comment]
I keep getting `yaml: line 16: did not find expected key` error.
`docker-compose.yaml`:
```yaml
version: '3.7'

services:

   nginx:
    container_name: nginx
    image: lscr.io/linuxserver/nginx:latest
    networks:
      - nginx-proxy
    ports:
      - 2080:80
      - 2443:443
    volumes:
      - ./config:/config
    restart: always

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    restart: always

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
     - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_BASE_URL}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always

networks:
  searxng:
    ipam:
      driver: default
  nginx-proxy:
    name: nginx-proxy-manager_default

volumes:
  caddy-data:
  caddy-config:
```

changes to `.env`
```
SEARXNG_HOSTNAME=searx.zimro.xyz
SEARXNG_BASE_URL=searx.zimro.xyz
#LETSENCRYPT_EMAIL=blank
```
`./config/nginx.conf`
```
user searxng;
worker_processes 1;
pid /run/nginx.pid;
include /etc/nginx/modules/*.conf;

events {
  worker_connections 768;
}

http {

  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 2048;
  server_tokens off;

  # server_names_hash_bucket_size 64;
  # server_name_in_redirect off;

  client_max_body_size 0;

  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  access_log /config/log/nginx/access.log;
  error_log /config/log/nginx/error.log;

  include /etc/nginx/http.d/*.conf;
  include /config/nginx/site-confs/*;
  #Removed lua. Do not remove this comment
  
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_min_length 10240;
    gzip_proxied expired no-cache no-store private auth;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml;

    
    server {
        listen  80;
        server_name  searxng.zimro.xyz;

    location / {

        set $target 127.0.0.1:2080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass $target;
        }
    }
  }
}  
daemon off;
```

**Comment by Emporea** [comment]
Is there a searxng environmental variable to specify a redis host?

**Comment by ziimro** [comment]
> Is there a searxng environmental variable to specify a redis host? And what is the preferred way to check if redis is actually working?

yes, i have that in `settings.yml`. And i run that on portainer i can see which containers start or not, im not fully sure if thats what you meant

**Comment by ziimro** [comment]
mistake close..

**Comment by Emporea** [comment]
Does it work for you?
I have a different setup with nginx but it works for me.

I disabled the redis container for now.

**Comment by Emporea** [comment]
Bzw you docker-compose file had slightly wrong indentation was slightly off, maybe thats where you error comes from?

```
version: "3.7"

services:
  nginx:
    container_name: nginx
    image: lscr.io/linuxserver/nginx:latest
    networks:
      - nginx-proxy
    ports:
      - 2080:80
      - 2443:443
    volumes:
      - ./config:/config
    restart: always

  redis:
    container_name: redis
    image: "redis:alpine"
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    restart: always

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - searxng
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_BASE_URL}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: always

networks:
  searxng:
    ipam:
      driver: default
  nginx-proxy:
    name: nginx-proxy-manager_default

volumes:
  caddy-data:
  caddy-config:

```
