### ISSUE TITLE
[Docker] 502 Bad Gateway: Connection refused

### ISSUE THREAD

**Issue by sweenu** [searxng/searxng-docker#97]
**Version**
2022.11.07-d3949269
(Just updated to make sure the problem is still there but I was using the build from 3 weeks ago and I had the same problem)

**How did you install SearXNG?**
Docker

**What happened?**
Everything works fine until after some point, I "randomly" get Bad Gateway 502. No log is outputted.
When that happens, if I go to my server and do:
```bash
curl $(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' searx):8080
curl: (7) Failed to connect to 172.24.0.3 port 8080 after 0 ms: Connection refused
```
I will try again and it will work and the above curl will output the html.

I thought it was a docker problem but I have several other containers on the same docker network and I never have this problem with them.
Also, the bind address is the default one: 0.0.0.0:8080.

I also have been using searxng for a two weeks without any problem. This problem started appearing very randomly.
I don't really know what next step I should take to debug this situation.

**Comment by SergioGlorias** [comment]
basically i had this problem too
making my instance (`search.serginho.dev`) not start anymore (https://github.com/searxng/searx-instances/discussions/278#discussioncomment-4722587)

and then even configure for it to use `network_mode: "host"` did not respond
and I was only able to boot back using the `BIND_ADDRESS=127.0.0.1:8888` environment (with host mode still enabled) (and yes i changed the port)

```yml
version: '3.7'

services:

  caddy:
    container_name: caddy
    image: docker.io/caddy:2-alpine
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost:80}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

  redis:
    container_name: redis
    image: "docker.io/redis:alpine"
    command: redis-server --save "" --appendonly "no"
    network_mode: "service:searxng"
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    network_mode: "host"
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - BIND_ADDRESS=127.0.0.1:8888
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  caddy-data:
  caddy-config:
```
